version: 2.0

workflows:
  version: 2
  test:
    jobs:
      - checkout
      - bundle_dependencies-35
          requires:
            - checkout
      - bundle_dependencies-36
          requires:
            - checkout
      - contract_unit:
          requires:
            - build_dependencies-36
      - intercontract_integration:
          requires:
            - contract_unit-36
      - crypto_unit:
          requires:
              - build_dependencies-36
      - network_unit:
          requires:
              - build_dependencies-36
      - keystore_unit:
          requires:
              - build_dependencies-36
      - character:
          requires:
              - crypto_unit-36
              - network_unit-36
              - keystore_unit-36

bundle_dependencies: &bundle_dependencies
  steps:
    - checkout
    - restore_cache:
        key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}
    - run:
        name: Install Pipenv itself
        command: pip install pipenv --upgrade
    - run:
        name: Install Python dependencies with Pipenv
        command: |
          pipenv install --three --dev --skip-lock
    - run:
        name: Install Solidity compiler
        command: |
          wget "https://github.com/ethereum/solidity/releases/download/${SOLC_VER}/solc-static-linux" -O "$(pipenv --venv)/bin/solc"
          chmod +x "$(pipenv --venv)/bin/solc"
        environment:
          SOLC_VER: "v0.4.24"
    - save_cache:
        paths:
          - "~/.local/share/virtualenvs/"
        key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}

jobs:
  bundle_dependencies-35:
    <<: *bundle_dependencies
    working_directory: ~/nucypher-depends-35
    docker:
      - image: circleci/python:3.5

  bundle_dependencies-36:
    <<: *bundle_dependencies
    working_directory: ~/nucypher-depends-36
    docker:
      - image: circleci/python:3.6

  contract_unit:
    parallelism: 4
    working_directory: ~/nucypher-depends-36
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}
      - run:
          name: Ethereum Contract Unit Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/blockchain/eth/contracts/unit/test_dispatcher.py \
            tests/blockchain/eth/contracts/unit/test_goverment.py

      - run:
          name: Ethereum Contract Issuer and Token Unit Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/blockchain/eth/contracts/unit/test_issuer.py \
            tests/blockchain/eth/contracts/unit/test_token.py

      - run:
          name: Ethereum Contract Escrow Unit Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/blockchain/eth/contracts/unit/test_miners_escrow.py
            tests/blockchain/eth/contracts/unit/user_escrow.py

      - run:
          name: Ethereum Contract Policy Manager Unit Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/blockchain/eth/contracts/unit/test_policy_manager.py

  intercontract_integration:
    working_directory: ~/nucypher-depends-36
    docker:
      - image: circleci/python:3.6
        environment:
          PY_DEP_VERSION: "py3.6"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}
      - run:
          name: Ethereum Inter-Contract Integration Test
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/blockchain/eth/contracts/integration

  crypto_unit:
    working_directory: ~/nucypher-depends-36
    docker:
      - image: circleci/python:3.6
        environment:
          PY_DEP_VERSION: "py3.6"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}
      - run:
          name: Crypto Character Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/crypto

  network_unit:
    working_directory: ~/nucypher-depends-36
    docker:
      - image: circleci/python:3.6
        environment:
          PY_DEP_VERSION: "py3.6"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}
      - run:
          name: Network Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/network

  keystore_unit:
    working_directory: ~/nucypher-depends-36
    docker:
      - image: circleci/python:3.6
        environment:
          PY_DEP_VERSION: "py3.6"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}
      - run:
          name: Keystore Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/keystore

  character:
    working_directory: ~/nucypher-depends-36
    docker:
      - image: circleci/python:3.6
        environment:
          PY_DEP_VERSION: "py3.6"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ .Environment.PY_DEP_VERSION }}
      - run:
          name: Character Tests
          command: |
            pipenv run pytest --cov=nucypher -v --runslow tests/characters
